name: Build for Android

on:
  push:
    branches: [master]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get

      - name: Set up signing config
        run: |
          echo "${{ secrets.ANDROID_KEY_BASE64 }}" | base64 -d - > upload-keystore.jks
          echo "${{ secrets.ANDROID_PROPERTIES_BASE64 }}" | base64 -d - > key.properties
          export X_KEYSTORE_PATH="$(pwd)/upload-keystore.jks"
          echo "X_KEYSTORE_PATH=$X_KEYSTORE_PATH" >> $GITHUB_ENV
          cp key.properties android/key.properties

      - name: Build APK
        run: flutter build apk --split-debug-info=./build-debug-files --flavor pro --release --split-per-abi --target-platform="android-arm64"
        env:
          X_KEYSTORE_PATH: ${{ env.X_KEYSTORE_PATH }}

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: oinkoin-arm64-v8a-fdroid-release.apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-fdroid-release.apk